### ISSUE TITLE
Integer values of strawtubes.ViewAngle 

### ISSUE THREAD

**Issue by hushchyn-mikhail** [ShipSoft/FairShip#182]
c.strawtubes.ViewAngle  in geometry/geometry_config.py can take only integer values. In other case it generates an error in macro/run_simScript.py: 

Traceback (most recent call last):
  File "/SHiPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/macro/run_simScript.py", line 279, in <module>
    modules = shipDet_conf.configure(run,ship_geo)
  File "/SHiPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/python/shipDet_conf.py", line 319, in configure
    Strawtubes.SetStereoAngle(ship_geo.strawtubes.ViewAngle)
TypeError: void strawtubes::SetStereoAngle(int stereoangle) =>
    could not convert argument 1 (int/long converion expects an integer object)

Steps to repeat:
1. Set up in geometry/geometry_config.py:
c.strawtubes.ViewAngle = 5.58
2. Run simulation:
macro/run_simScript.py

**Comment by olantwin** [comment]
Fixed in #490.
