### ISSUE TITLE
TMatrixTSym<double>::operator[](int rown) => could not convert argument 1

### ISSUE THREAD

**Issue by JLTastet** [ShipSoft/FairShip#290]
On the current master branch,
```
python "$FAIRSHIP"/macro/run_simScript.py
python "$FAIRSHIP"/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root
```
results in the following error:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/j/jetastet/sw/slc7_x86-64/FairShip/master-1/macro/ShipReco.py", line 142, in <module>
    SHiP.reconstruct()
  File "/afs/cern.ch/user/j/jetastet/sw/slc7_x86-64/FairShip/master-1/python/shipDigiReco.py", line 219, in reconstruct
    self.Vertexing.execute()
  File "/afs/cern.ch/user/j/jetastet/sw/slc7_x86-64/FairShip/master-1/python/shipVertex.py", line 47, in execute
    self.TwoTrackVertex()
  File "/afs/cern.ch/user/j/jetastet/sw/slc7_x86-64/FairShip/master-1/python/shipVertex.py", line 198, in TwoTrackVertex
    self.Vy[i] = covInv[i/10][i%10]
TypeError: none of the 2 overloaded methods succeeded. Full details:
  TMatrixTRow<double> TMatrixTSym<double>::operator[](int rown) =>
    could not convert argument 1 (int/long conversion expects an integer object)
  const TMatrixTRow_const<double> TMatrixTSym<double>::operator[](int rown) =>
    could not convert argument 1 (int/long conversion expects an integer object)
```

**Comment by ThomasRuf** [comment]
Fixed. Some missing //.
