### ISSUE TITLE
ShipReco.py problems after the last commit

### ISSUE THREAD

**Issue by PlaZMaD** [ShipSoft/FairShip#334]
ShipReco.py -g *some geofile name* -f *some FS output file name*
leads to 
"""
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_0/glass_upstreamtagger_171 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_0/glass_upstreamtagger_171 not valid
Error in <TClingBaseClassInfo::Offset>: There are multiple paths from derived class UpstreamTaggerHit to base class TObject.
Traceback (most recent call last):
  File "/sw/slc7_x86-64/FairShip/master-1/macro/ShipReco.py", line 141, in <module>
    SHiP.digitize()
  File "/sw/slc7_x86-64/FairShip/master-1/python/shipDigiReco.py", line 245, in digitize
    self.digitizeUpstreamTagger()
  File "/sw/slc7_x86-64/FairShip/master-1/python/shipDigiReco.py", line 683, in digitizeUpstreamTagger
    if hitsPerDetId.has_key(detID):
AttributeError: 'dict' object has no attribute 'has_key'
"""

Yesterday everything  worked fine for me.

**Comment by ThomasRuf** [comment]
Are the simulated data produced with the same FairShip version as used for the reconstruction? 
With the change of the Upstram Veto Tagger technology, you cannot reconstruct data which was produced with a different detector.

**Comment by olantwin** [comment]
If this was expected breakage, it would have been good to warn users on the mailing list.

While I understand that this change unavoidably creates some breakage, I did not have it on the radar since I did not follow the PR closely.

Maybe we can add a github label to pull requests which will probably break things?

**Comment by ThomasRuf** [comment]
The PR didn't broke any code, it broke backward compatibility with older data. I announced in the last ship week, that until we have a working 2020 geometry, there is no backward compatibility required for the master branch. Essentially, for any PR which changes the experimental setup, data produced with an earlier version becomes obsolete.
What is a github label?

**Comment by olantwin** [comment]
OK, I see.

In the right column when viewing an issue or pull request there are several additional pieces of information: assignees/reviewers, lables, projects, milestones etc.. The labels can be set quite freely by you (or anyone with push access) to give additional information regarding an issue/pull request.

In other projects I commonly see e.g.:

* "help wanted"
* "WONTFIX"
* "bug"
* "improvement"

These labels also appear in the overview of the issues/pull requests.

In addition to the common ones, some I could think of that could be useful to us in particular:

* "physics" : not just a code change and needs to be checked carefully for physics behaviour

**Comment by tugberk92** [comment]
Today, I used ShipReco with a geo output which had been created before the last commit.
It failed. The error message is below

>>>configured to process  999999  events from  /eos/experiment/ship/data/ALP/200329/sim/ALPACA_mass0.1_g1.000000e-07.root  starting with event  0  with option Yheight =  None  with vertexing True  and real pattern reco  
[INFO] Media file used: /afs/cern.ch/user/t/takmete/SHiPBuild/sw/slc7_x86-64/FairShip/master-1/geometry/media.geo
Traceback (most recent call last):
  File "/afs/cern.ch/user/t/takmete/SHiPBuild/FairShip/macro/ShipReco.py", line 107, in <module>
    modules = shipDet_conf.configure(run,ShipGeo)
  File "/afs/cern.ch/user/t/takmete/SHiPBuild/sw/slc7_x86-64/FairShip/master-1/python/shipDet_conf.py", line 144, in configure
    **ship_geo.muShieldWithCobaltMagnet, ship_geo.muShieldStepGeo) 
AttributeError: 'Config' object has no attribute 'muShieldWithCobaltMagnet'**

Then, I used a newly produced geo file. 
Now, It looks like reco is working OK with some error message. 
Just in case, let me share the related part of HTCondor error output, maybe it could help in understanding;

>>>Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_238 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_238 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_239 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_239 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_240 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_21/glass_upstreamtagger_240 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_169 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_169 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_170 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_170 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_171 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_16/glass_upstreamtagger_171 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_238 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_238 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_239 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_239 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_240 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger1_11/glass_upstreamtagger_240 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_169 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_169 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_170 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_170 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_171 not valid
Error in <TGeoNavigator::cd>: Path /cave_1/Upstream_Tagger_1/UpstreamTagger_6/glass_upstreamtagger_171 not valid

**Comment by olantwin** [comment]
I guess this can be closed.
