### ISSUE TITLE
UpstreamTaggerHit breaks running of digitization and reconstruction

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/FairShip#353]
python -i $SHIPBUILD/FairShip/macro/ShipReco.py ...
event  0
 aaaa -2497
 aaaa -2497
Error in <TClingBaseClassInfo::Offset>: There are multiple paths from derived class UpstreamTaggerHit to base class TObject.
Traceback (most recent call last):
  File "/media/disk0/SHiPBuild/FairShip/macro/ShipReco.py", line 141, in <module>
    SHiP.digitize()
  File "/media/disk0/SHiPBuild/sw/ubuntu2004_x86-64/FairShip/master-1/python/shipDigiReco.py", line 245, in digitize
    self.digitizeUpstreamTagger()
  File "/media/disk0/SHiPBuild/sw/ubuntu2004_x86-64/FairShip/master-1/python/shipDigiReco.py", line 683, in digitizeUpstreamTagger
    if hitsPerDetId.has_key(detID):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by ThomasRuf** [comment]
what is the motivation to have UpstreamTaggerHit inheriting from UpstreamTagger? 

class UpstreamTaggerHit : public ShipHit, UpstreamTagger

**Comment by ThomasRuf** [comment]
removing the inheritance solves the ROOT error. Other issue remains.

**Comment by ThomasRuf** [comment]
reason for the problem, the method digitizeUpstreamTagger is not python3 compliant. Should not have been committed.

Removed. dict.has_key() – use the in operator instead.

**Comment by ThomasRuf** [comment]
after having fixed this, I now get thousand of lines:
event  0
 aaaa -2497
 aaaa -2497
 aaaa -2497
 aaaa -2497
 aaaa -2497
 aaaa -2497
 aaaa -2497
 aaaa -2497

**Comment by ThomasRuf** [comment]
fixes committed and pushed to master branch
