### ISSUE TITLE
FairShip crashes during Geant4 setup

### ISSUE THREAD

**Issue by Element-126** [ShipSoft/FairShip#96]
On latest master (commit `724a49c0c045d4131b8426952be7fdbc6891cf18`), when running FairShip with the default settings on LXPLUS,
```
$ python "$FAIRSHIP"/macro/run_simScript.py
```
I get the following traceback:
```
[INFO   ] Monte Carlo Engine Initialisation with: TGeant4
Calling addVMCFields
Traceback (most recent call last):
  File "/afs/cern.ch/user/<redacted-username>/FairShip-JL/FairShipRun/../FairShip/macro/run_simScript.py", line 495, in <module>
    fieldMaker = geomGeant4.addVMCFields(ship_geo, '', True)
  File "/afs/cern.ch/user/<redacted-username>/FairShip-JL/FairShip/python/geomGeant4.py", line 140, in addVMCFields
    fieldMaker = ROOT.ShipFieldMaker(verbose)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  ShipFieldMaker::ShipFieldMaker(const string& inputFile, bool verbose = kFALSE) =>
    could not convert argument 1
  ShipFieldMaker::ShipFieldMaker(const ShipFieldMaker&) =>
    could not convert argument 1
gMC deleted
```
Everything was working fine as of `912ad6997e76c2c349e28a38ea335efa24b6fd1b`.

Any idea what could be the cause ?

**Comment by Element-126** [comment]
I might have messed up here. That would be really dumb on my part, but I did quite a lot of branch-hopping in the last few days (had to rebase several dozen commits on master), and I might have forgotten to recompile it after the last rebase.

I will recompile and check if it works now. If that is the case, you can probably delete this issue altogether.

**Comment by Element-126** [comment]
Ok, you were right: I messed up here :neutral_face:  Sorry for the inconvenience.

BTW, I have a branch with the updated HNL branching ratios (used for PBC) and a significant number of bug fixes. I will rebase it on the current master and send a PR as soon as it has been reviewed by my collaborators.

Feel free to delete this issue if you have the necessary privileges for that.
